--시스템 계정에서 계정생성
CREATE USER ncsUser IDENTIFIED BY ncsUser;
GRANT CONNECT TO ncsUser;
GRANT RESOURCE TO ncsUser;
GRANT DBA TO ncsUser;


--NcsUser으로 실행 테이블 생성 
CREATE TABLE MEMBER(
MEMBER_ID VARCHAR2(30) PRIMARY KEY,
MEMBER_PWD VARCHAR2(100) NOT NULL,
MEMBER_NM VARCHAR2(15) NOT NULL,
MEMBER_ENROLL_DT DATE DEFAULT SYSDATE
);

desc member;
SELECT * FROM MEMBER;